### ISSUE TITLE
create starter folder 

### ISSUE THREAD

**Issue by SOSANA** [jesseskinner/reactjs-radio-group#1]
Hey was checking out your YouTube video series and decided to check out your repo. You should make a starter folder so others can follow along.

Cheers!

**Comment by jesseskinner** [comment]
Hey, thanks for the suggestion! I've used git tags to track the various stages of development. You can checkout these tags: start, part1, part2, etc.

**Comment by SOSANA** [comment]
Awesome! And thanks for the sweet series!

**Comment by jesseskinner** [comment]
Thanks so much!
